language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UeRPxmqFw2jXdPLwTe0OGioTwNI1P5w75WEjnwMiD7vKDK2qyM2SmHNsJmK+Ei0n5jNbmQGHftmL7eBSOTS949h+QyMNE5Yli8guvS84l3nycHGRDuUcabIYqtg+kwT16SwNabywaIPAEpRs/2H3b3neHFnztQYflVT9Ng8ynHQNQNomJoVLy7IW5jcWSnNaE11KpAINpuqAgh7FyJPNhqr06Ieel7Ac1rLR/yOvA/SNRgBnMKNszYaeR20YLvcVoHwjMZ3rT2btPsbUtiqfNSwrdUijno46pFVGb1Zf04f57q1joazrhgAMlmkYGtfAqXN2Bnvngp+LElT0uCaORIE+uXf3pAmOocIhPlJt7crAJVxoKKS0zScKenKkb634Whupt+jBeFl/CTy0Jiz+Fbaji4N5gy+CVXaAVyy4b8FWFhBygoIem87y0N2QpBqBh1cug7CgSIQ3J4pTYKhuIxs8NeoPJdFgcCixYeF1kr/nv9I3h2hzMgGwcNB17PH6ZtA486D1QI9zHKyNUJzsjJYHHpZ1oxD6Itc2SKGZDUUVvol0WifGRfbKcb7cgj8IXht4KI5spCyuGvxkBkmyM7XNoG+pxP8fMc2/CArGcXlzJfevw9nJR/OVuF3EKuSlwCkP5jkf91YB9pK3xenY/nFk2sRMyBJdDOfHHHqJ7ok=
  app: fathomless-plains-59362
  on:
    repo: jayshol/puzzle-react
